version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
      #      - sam package --template-file template.yml --s3-bucket codepipeline-serverless --output-template-file packaged-template.yml
      - sam package --template-file template.yml --s3-bucket "codepipeline-serverless"
#artifacts:
#  files:
#    - packaged-template.yml
